### ISSUE TITLE
Try the digital gyroscope MPU-6500

### ISSUE THREAD

**Issue by Peque** [Theseus/bulebule#191]
With pins PB12-PB15.

[Datasheet](https://www.invensense.com/wp-content/uploads/2015/02/MPU-6500-Datasheet2.pdf).
[Register map](https://www.invensense.com/wp-content/uploads/2015/02/MPU-6500-Register-Map2.pdf).

![mpu6500](https://user-images.githubusercontent.com/526577/35707440-f6513dda-07a9-11e8-842d-7044b0b9ad58.png)

**Comment by cua-cua** [comment]
DataSheet reference
https://www.invensense.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf

**Comment by Peque** [comment]
We should try to read actual values at 20 MHz before closing this issue.
