### ISSUE TITLE
Review new PCB modules

### ISSUE THREAD

**Issue by Peque** [Theseus/bulebule#217]
- [Gyro](https://upverter.com/upn/revision/eb947b59b19013ef/)
- [Motor driver](https://upverter.com/upn/revision/b523f1941c46ee91/)
- [Switch](https://upverter.com/upn/revision/05acec19143ac780/)

**Comment by Peque** [comment]
@cua-cua Can you have a look at them? Just basic stuff like dimension and correct pin-out. :blush:

**Comment by cua-cua** [comment]
It is ok enough :)
