### ISSUE TITLE
Integrate gyroscope

### ISSUE THREAD

**Issue by Peque** [Theseus/bulebule#255]
Currently it is integrated in the hardware, but it missing some software integration.

Configuration, calibration, integration in control (to measure angular velocity).

References:

- https://github.com/AYATAKA-WORKs/AliCe/blob/master/src/gyro.cpp

**Comment by cua-cua** [comment]
- Create setup gyro function
- Create log function to connect gyro with spinete

**Comment by Peque** [comment]
When I started playing around with the gyro I wrote this (do not know why or if it may be useful for your... :sweat_smile):

```c
	/* Reset gyro restoring default settings */
	gyro_write_register(GYRO_PWR_MGMT_1, 0x80);
	sleep_ticks(100);
	/* Reset signal path */
	gyro_write_register(GYRO_SIGNAL_PATH_RESET, 0x07);
	sleep_ticks(100);
	/* Set SPI mode, reset DMP + FIFO + SIG */
	gyro_write_register(GYRO_USER_CTRL, 0x1d);
	sleep_ticks(1000);
	printf("---\n");
	while (1) {
		reading = gyro_who_am_i();
		printf("I am %03i\n", reading);
		sleep_ticks(1000);
	}
```

**Comment by Peque** [comment]
I think you might not need to configure anything in the gyro to read at 20 MHz.

You do need to make sure that, after gyro configuration, we change SPI frequency to ~20 MHz (as close as possible). We should be able to read at that speed.

**Comment by Peque** [comment]
This might be useful as a reference:

- https://github.com/NordicPlayground/nrf52-quadcopter

Also, configuring a 6500 should be pretty similar (if not exact) to a 9250, so these might be useful as well:

- https://github.com/bolderflight/MPU9250
- https://github.com/brianc118/MPU9250

**Comment by cua-cua** [comment]
Requirements:
- Maximum speed: 90º on 80 ms -> 1125º/s
- Minimum sampling: 1ms (1MHz)
- Read gyro on axe Z positive
